global:
  scrape_interval: 5s # Cứ 5 giây đi lấy dữ liệu 1 lần

scrape_configs:
  - job_name: 'nodejs-backend'
    static_configs:
      # pc_inventory là tên container, 3000 là cổng của Node.js
      - targets: ['pc_inventory:3000']