{
 "title": "Hệ thống bán pc",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Tổng số sản phẩm",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "inventory_total_products", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tổng số người dùng",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "inventory_total_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Hệ thống uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up{job=\"nodejs-backend\"}[30d]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lưu lượng truy cập",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(inventory_http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sức khỏe server",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"nodejs-backend\"}[1m]) * 100",
     "legendFormat": "CPU"
    },
    {
     "expr": "(nodejs_heap_size_used_bytes{job=\"nodejs-backend\"} / nodejs_heap_size_total_bytes{job=\"nodejs-backend\"}) * 100",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Log hệ thống",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{container=\"pc_nginx\"} |= ``",
     "maxLines": 20
    }
   ]
  }
 ]
}