apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: my_prometheus_uid
    access: proxy
    url: http://pc_prometheus:9090
    isDefault: true
  - name: Loki
    type: loki
    uid: my_loki_uid
    access: proxy
    url: http://pc_loki:3100