FROM node:20-alpine
WORKDIR /usr/src/app

COPY package*.json ./

RUN npm config set registry http://registry.npmjs.org/ && \
    npm install --network-timeout=100000

COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]